# Generated by Django 4.2.4 on 2023-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='book_title',
            field=models.CharField(default='Book Title', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
