# Generated by Django 4.2.4 on 2023-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_name_item_book_title_item_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='book_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.TextField(default='-'),
        ),
    ]
