# Generated by Django 4.2.5 on 2023-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_book_title_item_name_item_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Book',
        ),
    ]
